### ISSUE TITLE
Multiplayer frag limit set to 0 by default

### ISSUE THREAD

**Issue by Ripper00420** [JohnnyonFlame/SDLQuake2#1]
Without a keyboard and the ability to raise the frag limit above 0, you can still play but cannot win a deathmatch.

I’m using WiFi adapters and 2 RG350M devices

**Comment by JohnnyonFlame** [comment]
You'll need to either implement the configuration menus or a launcher akin to what I made for odamex. I don't have any current plans to see it through right now, juggling enough projects already.

**Comment by Ripper00420** [comment]
I honestly have no idea how to do this, so I’m out of luck then. I’ve been playing Quake 3 Arena because it sets 20 by default, but was hoping this was still actively being worked on. Thanks for your email 💯

**Comment by JohnnyonFlame** [comment]
If you don't need to actually change it arbitrarily, just to a default value, then set the cvar on an `autoexec.cfg` file and it will be set every time by default.

**Comment by Ripper00420** [comment]
Firstly, is cvar a line in the autoexec.cfg, and secondly will it effect the config.cfg in the RG350 ported version that I’m using now?

Would I just place the autoexec.cfg in the same folder as the config.cfg for it to work?

**Comment by Ripper00420** [comment]
I got it working now, and thank you so very much for the information 

I added an autoexec.cfg with this line added
fraglimit “20”

**Comment by JohnnyonFlame** [comment]
Have fun!
